source import_data/Chamber.sql;
source import_data/State.sql;
source import_data/District.sql;
source import_data/Congress.sql;
source import_data/Session.sql;
source import_data/Legislator.sql;
source import_data/Term.sql;
select 'import bill';
source import_data/Bill_110.sql;
select 'import rest';
source import_data/Subject_110.sql;
source import_data/Amendment_110.sql;
source import_data/Vote_110.sql;
source import_data/Legislator_Vote_110.sql;
select 'import bill';
source import_data/Bill_111.sql;
select 'import rest';
source import_data/Subject_111.sql;
source import_data/Amendment_111.sql;
source import_data/Vote_111.sql;
source import_data/Legislator_Vote_111.sql;
select 'import bill';
source import_data/Bill_112.sql;
select 'import rest';
source import_data/Subject_112.sql;
source import_data/Amendment_112.sql;
source import_data/Vote_112.sql;
source import_data/Legislator_Vote_112.sql;
select 'import bill';
source import_data/Bill_113.sql;
select 'import rest';
source import_data/Subject_113.sql;
source import_data/Amendment_113.sql;
source import_data/Vote_113.sql;
source import_data/Legislator_Vote_113.sql;
select 'import bill';
source import_data/Bill_114.sql;
select 'import rest';
source import_data/Sponsor_114.sql;
source import_data/Subject_114.sql;
source import_data/Amendment_114.sql;
source import_data/Vote_114.sql;
source import_data/Legislator_Vote_114.sql;
select 'import bill';
source import_data/Bill_115.sql;
select 'import rest';
source import_data/Sponsor_115.sql;
source import_data/Subject_115.sql;
source import_data/Amendment_115.sql;
source import_data/Vote_115.sql;
source import_data/Legislator_Vote_115.sql;
